### ISSUE TITLE
Determine the best way to drive robot in auto

### ISSUE THREAD

**Issue by bb20basketball** [cboy116/Team-4480-Code-2018#15]
In previous years, I've used just a PID loop to get to a certain location on the field. However, this isn't the best way to do it. There is even a better way with motion profiling and path planning. 

I am going to research how intense motion profiling is and if it is worth us to implement.

**Comment by bb20basketball** [comment]
It looks like the Talon SRX Motion Magic is what will work best for us. We just have to wait until it has been ported to RobotPy.

**Comment by Brandutchmen** [comment]
How long will that be? This season or no?

**Comment by bb20basketball** [comment]
@Brandutchmen February 10th + 11th

**Comment by bb20basketball** [comment]
Turns out pathfinder is harder than it seems. Just doing basic straight-turn-straight for auto
